# Site settings
title: Adventures of a sales guy
header-img: img/home-bg.png
email: sweinstein27@gmail.com
copyright_name: sweinstein27
description: > # this means to ignore newlines until "baseurl:"
  My journey from sales to development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sweinstein27
learn_profile: sweinstein27
email_username: sweinstein27@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
